### PR TITLE
transcoding is done in addition to search

### PR DESCRIPTION
**Pull request by matkoniecz**
Even if transcoding would be faster than search it would still incur performance penalty

### CODE REVIEW

**Review by BurntSushi — APPROVED** [review]
Thanks!

**Comment by BurntSushi** [comment]
I wish there were a way to have CI bleat about 79 column violations, but it's not a rule I enforce 100% strictly. e.g., URLs and sometimes even code going over 79 columns is okay when that's the clearer path. But alas, such cases call for human judgment.

**Comment by matkoniecz** [comment]
Maybe some bot that would comment on PR "you added new lines in XXX file longer than N characters, typically this is unwanted, see this contributing.md section for more info"?

**Comment by matkoniecz** [comment]
I just checked and I see no CONTRIBUTING.md file at all (if that docs exist somewhere then making link-only CONTRIBUTING.md is still a good idea to make easy to find them)

For bot itself - I have seen some code coverage monitor bots posting, Visual Studio Code has some bot actions on issue tracker (automatically and triggered). See https://github.com/microsoft/vscode/issues/137641#issuecomment-975481667 https://github.com/microsoft/vscode-github-triage-actions

But I have no direct experience with maintaining, making or using something like that.

**Comment by BurntSushi** [comment]
Aye thanks, I created #2080 to track your idea.

**Pull request merged**
