### PR TITLE
fix profile showing command for powershell

### PR DESCRIPTION
**Pull request by santagada**
change the profile showing command to one that matches the microsoft article linked, as its simpler and the old one didn't work at least on windows 10 creators edition.

### CODE REVIEW

**Comment by DoumanAsh** [comment]
Hmm... it is rather strange as this command works on my win10
But it might depend on powershell version...

Anyway i didn't know that you could print content of variable like that. It is definitely better!

**Comment by BurntSushi** [comment]
@santagada Does this work on older versions of Windows?

**Comment by elirnm** [comment]
@BurntSushi It works on my Windows 7, which is the oldest OS Powershell supports.

**Comment by BurntSushi** [comment]
@elirnm Thanks for the confirmation!

**Pull request merged**
