### PR TITLE
Snapcraft definition for building ripgrep snaps.

### PR DESCRIPTION
**Pull request by tasdomas**
Snaps are a new application packaging approach that allows for better isolation. This PR introduces a snapcraft.yaml file that allows building ripgrep snaps using the [snapcraft](http://snapcraft.io) tool.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Hmm. I'm honestly not sure when I should merge this or not. I know that at least as of right now, I have a hard enough time maintaining the brew formula (I'm not a Mac user), so I worry that this will bitrot easily. In particular, I've never used or heard of this tool.

Is there an established way of maintaining snaps out-of-tree? I think that's what I would prefer at the moment.

**Comment by anuragsoni** [comment]
@tasdomas @BurntSushi Since snapcraft (the snap package builder) can pull source from git it can live out-of-tree. I was actually trying out building a snap package today before I saw this pull request :)

I believe the only change required to the yml file would be the following.
```
parts:
  rg:
    plugin: rust
    source: git://github.com/BurntSushi/ripgrep
    source-tag: 0.2.6

```

**Comment by anuragsoni** [comment]
Also, i'm not sure how common is it for snap packages to be used outside of Ubuntu for now, but I guess now they offer installation on arch, fedora and opensuse so that should cover a lot of different flavors!

**Comment by tasdomas** [comment]
@BurntSushi, @anuragsoni - having the snap build out of tree is fine.

**Comment by BurntSushi** [comment]
@tasdomas @anuragsoni Thanks for the info. I think I'd rather take that route for now!

**Pull request closed without merging**
