### PR TITLE
Add *.svelte to js types

### PR DESCRIPTION
**Pull request by zarkone**
filetype of https://svelte.dev/

### CODE REVIEW

**Comment by BurntSushi** [comment]
Hmmm, I'm not so sure about this. I don't know anything about svelte, but looking at your link, svelte files look more like HTML files to me. In particular, the `js` type in ripgrep does _not_ contain HTML files, even though they can contain Javascript inside them.

Would others care to weigh in on this?

**Comment by zarkone** [comment]
@BurntSushi well, svelte files looks pretty much the same as `*.vue` files, which mask is in `js` category

**Comment by zarkone** [comment]
for me personally it is more convenient to have both `vue` and `svelte` in js, but it is arguable of course

**Comment by BurntSushi** [comment]
@zarkone I think it'd be a useful exercise to evaluate this addition on its own. It could have been a mistake to add vue to js, I don't know. Are svelte (or vue) files _principally_ Javascript?

**Comment by zarkone** [comment]
principally no, i think. This files contains html,css and js -- all mixed

**Comment by BurntSushi** [comment]
All right, so if it's not principally Javascript, then I'm not quite sure I feel comfortable putting it under the `js` type.

I'd be happy to be overruled by this, but I think I'd want to see some consensus from relevant stakeholders.

**Pull request closed without merging**
