### PR TITLE
types: add webidl (*.webidl)

### PR DESCRIPTION
**Pull request by hoodie**
just to be sure

### CODE REVIEW

**Comment by evilpie** [comment]
Thanks! Mozilla actually exclusively uses that extension: https://searchfox.org/mozilla-central/search?q=webidl&path=

**Comment by hoodie** [comment]
@evilpie you mean only mozilla uses that extension? because there are also lots of .idl files in there too

**Comment by evilpie** [comment]
I mean Mozilla exclusively uses `.webidl` to mean Web IDL files. `.idl` is used for XPIDL files.

**Comment by hoodie** [comment]
you never stop to learn :)

**Pull request merged**
