### PR TITLE
ignore: add grouped defaults toggle

### PR DESCRIPTION
**Pull request by durka**
Adds a single function to toggle all the enabled-by-default options on `WalkBuilder`. I implemented this for [my crate](https://github.com/haptics-nri/bible-extractor/blob/76769934d69c6cd9857884e91e30eb2f6370973a/src/main.rs#L98) because I wanted a parallel directory iterator but I don't actually need the fancy ignore stuff. Feel free to reject if that isn't an intended use case.

### CODE REVIEW

**Comment by BurntSushi** [comment]
@durka Hmmmm. I guess I'm in principle OK with something like this, but I think the name and/or documentation isn't quite clear enough. Can we come up with something better? For example, I think it would be clearer if instead of focusing on "defaults" we focused on "filtering." So I think the docs for this function should explicitly call out that the filters for this iterator are all enabled by default, and this this function can be used to toggle their presence as a group. I think we should also say that filters may be selectively enabled by the caller after using this.

**Comment by durka** [comment]
Maybe `default_filters` or `standard_filters`?

**Comment by BurntSushi** [comment]
I think I like `standard_filters`.

**Comment by durka** [comment]
I changed the name and added more docs.

**Pull request merged**
