### PR TITLE
ci: rebuild release infrastructure on GitHub Actions

### PR DESCRIPTION
**Pull request by BurntSushi**

### CODE REVIEW

**Comment by sersorrel** [comment]
This may be unavoidable, but just so you know: this is sending out a fair few email notifications to people who watch releases on this repo, I've had at least 10 so far.

**Comment by BurntSushi** [comment]
I don't know how to avoid it, sorry. I'm working on moving the release infrastructure over to GitHub, so once that's done, hopefully this will pass.

I put the word "TEST" in the release, so if you really can't abide it, then create an email filter.

**Comment by sersorrel** [comment]
No worries, it's not a big deal!

**Comment by BurntSushi** [comment]
Looks like I _finally_ got it working, so hopefully things will be quieter now. Thanks!

**Pull request merged**
