### PR TITLE
adding cs filetype for ease of use.

### PR DESCRIPTION
**Pull request by theamazingfedex**

### CODE REVIEW

**Comment by BurntSushi** [comment]
What file type is this?

**Comment by theamazingfedex** [comment]
.cs for csharp

**Comment by BurntSushi** [comment]
OK, so you're proposing that we have two names for the same file type. I'd like to avoid this, but we do have precedent for it, so I guess we can merge.

**Comment by theamazingfedex** [comment]
I'm not sure if Rust will allow for this, but if there were a way to have multiple keys for each type, we could avoid having two distinct entries for it. 
Probably something like the following:
``` Rust
const DEFAULT_TYPES: &'static [(&'static [&'static str], &'static [&'static str])] = &[
  (&["cs", "csharp"], &["*.cs"]),
  (&["md", "markdown"], &["*.markdown", "*.md", "*.mdown", "*.mkdn"])
]
```

**Comment by BurntSushi** [comment]
I'm actually fine with the duplication in source code for now. What concerns me more is the UX. That is, having multiple ways to refer to the same thing.

> If this is possible, it would also require some slight refactoring of the rg type checking module.

At least the `Type` matcher itself could be made to duplicate the definitions, even if they aren't duplicated in the source code, so I think that's fine.

**Pull request merged**
