### PR TITLE
Incorporated faster line count

### PR DESCRIPTION
**Pull request by llogiq**
Thanks for the hint; here's the faster linecount for your ripgrep utility.

### CODE REVIEW

**Comment by llogiq** [comment]
See [newlinebench](/llogiq/newlinebench) for more information.

**Comment by Byron** [comment]
I am so looking forward to see this PR land, just because line counts are enabled by default and are something people do expect to see anyway. Looking at the benchmarks on @BurntSushi 's blog, being faster at this will be absolutely noticeable !

**Comment by BurntSushi** [comment]
It will likely only be noticeable when searching very large files.

But yes, I believe @llogiq is working on putting this in a crate since there have been other developments. I would also like to understand the algorithm and audit it for safety before merging, so it might be a bit. Hang tight.

**Comment by Byron** [comment]
Sounds very reasonable ! I will happily use the fastest and best 'out-of-the' best experience then, to soon be able to tout it just became a little bit faster :).

**Comment by llogiq** [comment]
Yeah, I want to strip down the use of `unsafe`, put that in its own crate, document the bit twiddling and the rationale better and then I'll update.

Of course you can pull this now (as it'll already be faster), and I'll push a new PR when it's ready.

**Comment by BurntSushi** [comment]
@llogiq Thanks! I have a nit about changes to `Cargo.toml`.

Other than that, I need to audit `bytecount` before I can merge this. I'm not sure when I'll get to that. Maybe this weekend? It would help if there was an explanation of how it works. cc @Veedrac

**Comment by Veedrac** [comment]
@BurntSushi I've got [a new version](https://github.com/llogiq/bytecount/pull/2) that should be easier to audit.

The basic idea is that the function `vector_not` turns any null bytes in a `usize` into `1`s and any others into `0`s. I go along four `usize`s at a time, adding these into a `counts` array. Every 255 quadruplets, I flush the bytewise counts into the total count to prevent any byte from overflowing.

**Comment by llogiq** [comment]
I have a somewhat thorough explanation on [my blog](https://llogiq.github.com/2016/09/27/count.html).

**Comment by llogiq** [comment]
Any updates on this?

**Comment by BurntSushi** [comment]
No.

**Comment by Veedrac** [comment]
FWIW, a newer version has SIMD support, which is a lot faster.

**Comment by BurntSushi** [comment]
I merged this in 4368913d8fc174cf21fcb9d04b24136ceb87a393 with a squash and a regression test for #128. Sorry it took so long @llogiq but thank you!

**Comment by BurntSushi** [comment]
This did wind up with quite a nice speed up! Comparing old master (`rg-master`) with `rg` using `avx-accel`.

First, a base line with no line counting:

```
[andrew@Cheetah subtitles] time rg-master 'Sherlock Holmes' OpenSubtitles2016.raw.en | wc -l
5107

real    0m1.578s
user    0m1.213s
sys     0m0.363s
[andrew@Cheetah subtitles] time rg 'Sherlock Holmes' OpenSubtitles2016.raw.en | wc -l
5107

real    0m1.533s
user    0m1.140s
sys     0m0.390s
```

And now with line counting:

```
[andrew@Cheetah subtitles] time rg-master -n 'Sherlock Holmes' OpenSubtitles2016.raw.en | wc -l
5107

real    0m4.260s
user    0m3.867s
sys     0m0.397s
[andrew@Cheetah subtitles] time rg -n 'Sherlock Holmes' OpenSubtitles2016.raw.en | wc -l
5107

real    0m2.131s
user    0m1.810s
sys     0m0.323s
```

Twice as fast!

**Comment by llogiq** [comment]
Cool!

**Pull request closed without merging**
