### PR TITLE
adding .mak extension for makefile filetype.

### LINKED ISSUE #217: Makefile type list is missing "*.mak"
Comparing several _greppers_:

rg --type-list:
`make: *.mk, Gnumakefile, Makefile, gnumakefile, makefile`

ack --help-types
`--[no]make         .mk; .mak; makefile; Makefile; Makefile.Debug; Makefile.Release`

sift --list-types
`make           :Makefile *.mak`

I am missing the ***.mak** pattern.

By the way, this tool is awesome.
Good work. Keep it up!

### PR DESCRIPTION
**Pull request by theamazingfedex**
Resolves #217

### CODE REVIEW

**Comment by BurntSushi** [comment]
Can you mention that this "Fixes #217" in the commit message?

(I'm trying to keep PRs lined up with issues.)

**Comment by theamazingfedex** [comment]
sure, i'll amend that real quick

**Comment by theamazingfedex** [comment]
Done.

**Comment by BurntSushi** [comment]
Thanks! Once the CI goes through I'll merge.

**Comment by BurntSushi** [comment]
Bah, stupid Darwin. This is good.

**Pull request merged**
