### PR TITLE
add yocto file types

### PR DESCRIPTION
**Pull request by syedelec**
add file types for embedded linux Yocto project : https://www.yoctoproject.org/

### CODE REVIEW

**Comment by BurntSushi** [comment]
Thanks so much!

**Comment by lilianmoraru** [comment]
I would like to point 2 issues:
- Yocto is too generic. These files are specific to 1 tool, called BitBake.
- This is not a complete list. It also has files akin' to headers in C/C++, where the content is inserted directly inside the *.bb* files.

**Comment by syedelec** [comment]
@lilianmoraru, thank you for pointing out these remarks, what do you suggest ?
Actually, I was thinking using `-tbb` but it is too explicit and may create confusion since people may think it only includes `.bb` files.

**Comment by lilianmoraru** [comment]
This would be in the same ballpark as `sh`, `cpp`, `c`, `asm`, etc...

**Comment by lilianmoraru** [comment]
I scrolled through the reference manual and it seems to have these extensions:
```
.bb
.bbappend
.bbclass
.conf
.inc
```
It also can call into Python code, but I guess this could be excluded.

**Comment by syedelec** [comment]
Multiple languages and configurations use `.conf` (e.g `rc.conf`, `syslog.conf` etc...) and `.inc` (e.g in C/C++, PHP and VIM config) as file type. IMHO, they cannot be included in specific yocto/bitbake file types. @BurntSushi, what do you think ?

**Comment by BurntSushi** [comment]
I don't have a lot of domain knowledge here, but it is OK for file types to overlap. For example, `-tc` and `-tcpp` will both search `*.h` files.

**Pull request merged**
