### PR TITLE
moving .ts from typoscript to TypeScript

### PR DESCRIPTION
**Pull request by Mellbourn**
The TypeScript language is in the top ten of the [most popular programming languages](https://pypl.github.io/PYPL.html).

Typoscript is a custom language for the TYPO3 CMS, that is far less used.

I think that the `.ts` extension should belong to the `typescript` type in ripgrep, not typoscript.

### CODE REVIEW

**Comment by BurntSushi** [comment]
The `ts` file type already exists. That's for typescript.

File types don't own extensions. Multiple file types may have the same globs.

**Comment by Mellbourn** [comment]
Right you are. It was a bit confusing that I could start to type `typ` in the shell and the completion system suggested `typoscript`, which I initially thought was a typo :D

**Comment by matkoniecz** [comment]
So 

```
    ("typescript", &["*.ts"]),
    ("typoscript", &["*.ts", "*.typoscript"]),
```

would be better, right?

**Comment by BurntSushi** [comment]
This is wrong. Firstly, if `ts` and `typescript` are referring to the same thing, then they should have the same globs. This PR does not have that. Secondly, this PR removes a glob from `typoscript` without justifying it.

**Pull request closed without merging**
