### PR TITLE
chore: fix some comments

### PR DESCRIPTION
**Pull request by tgolang**

### CODE REVIEW

**Comment by atouchet** [comment]
The first change was fixed in #2776.

**Comment by tgolang** [comment]
> ripgrep/crates/core/messages.rs

Thanks!

**Comment by tgolang** [comment]
> The first change was fixed in #2776.

Thansk.

Modified

**Comment by tgolang** [comment]
Please review again.

**Comment by tgolang** [comment]
If anything need I to do, Please feel free to tell me.

**Review by BurntSushi — APPROVED** [review]

**Pull request merged**
